package Model.UnitPackage;

public enum UnitStatus {
    ACTIVE, SLEEP, ALERT, FORTIFY, HEAL, SETTLE,
    SIEGEPREP, RANGEDATTACK, RAID, FOUNDCITY,
    DO_NOTHING, BUILD, MOVE, REMOVE_RESOURCE
}
