package Model.UnitPackage;

public enum UnitType {
    ARCHER, CHARIOT_ARCHER, SCOUT, SETTLER, SPEARMAN, WARRIOR,
    WORKER, CATAPULT, HORSEMAN, SWORDSMAN, CROSSBOWMAN, KNIGHT,
    LONGSWORDSMAN, PIKEMAN, TREBUCHET, CANNON, CAVALRY, LANCER,
    MUSKETMAN, RIFLEMAN, ANTI_TANK_GUN, ARTILLERY, INFANTRY, PANZER,
    TANK
}
