package Model.UnitPackage;

public enum UnitStatus {
    ACTIVE, SLEEP, ALERT, FORTIFY, HEAL, SETTLE,
    SIEGEPREP, RANGEDATTACK, RAID, FOUND_CITY,
    DO_NOTHING, BUILD_IMPROVEMENT, REPAIR_IMPROVEMENT , MOVE, REMOVE_RESOURCE,
    WAKE, CANCEL_MISSION, HAS_PATH
}
