package Client.Model;

import javafx.scene.image.Image;


public enum ImageBase {

    CITY_0(new Image("Pictures/tiles/City0.png")),
    CITY_1(new Image("Pictures/tiles/city1.png")),
    CITY_2(new Image("Pictures/tiles/City2.png")),
    CITY_3(new Image("Pictures/tiles/City3.png")),
    CITY_4(new Image("Pictures/tiles/City4.png")),
    CLOUD(new Image("Pictures/tiles/cloud.png")),
    DELTA(new Image("Pictures/tiles/DELTA.png")),
    DESERT(new Image("Pictures/tiles/desert.png")),
    FOREST(new Image("Pictures/tiles/FOREST.png")),
    GRASS(new Image("Pictures/tiles/GRASS.png")),
    GRASS_MARSH(new Image("Pictures/tiles/GRASS_MARSH.png")),
    HILL(new Image("Pictures/tiles/HILL.png")),
    ICE(new Image("Pictures/tiles/ICE.png")),
    JUNGLE(new Image("Pictures/tiles/JUNGLE.png")),
    MOUNTAIN(new Image("Pictures/tiles/MOUNTAIN.png")),
    OASIS(new Image("Pictures/tiles/OASIS.png")),
    OCEAN(new Image("Pictures/tiles/OCEAN.png")),
    PLAIN(new Image("Pictures/tiles/PLAIN.png")),
    PLAIN_MARSH(new Image("Pictures/tiles/PLAIN_MARSH.png")),
    TUNDRA(new Image("Pictures/tiles/TUNDRA.png")),
    SNOW(new Image("Pictures/tiles/SNOW.png")),
    FOOD_1(new Image("Pictures/tiles/Food1.png")),
    FOOD_2(new Image("Pictures/tiles/Food2.png")),
    FOOD_3(new Image("Pictures/tiles/Food3.png")),
    FOOD_4(new Image("Pictures/tiles/Food4.png")),
    PRODUCTION_1(new Image("Pictures/tiles/Production1.png")),
    PRODUCTION_2(new Image("Pictures/tiles/Production2.png")),
    PRODUCTION_3(new Image("Pictures/tiles/Production3.png")),
    PRODUCTION_4(new Image("Pictures/tiles/Production4.png")),
    GOLD_1(new Image("Pictures/tiles/Gold1.png")),
    GOLD_2(new Image("Pictures/tiles/Gold2.png")),
    GOLD_3(new Image("Pictures/tiles/Gold3.png")),
    GOLD_4(new Image("Pictures/tiles/Gold4.png")),
    RIVER_E(new Image("Pictures/tiles/RIVER_L.png")),
    RIVER_O(new Image("Pictures/tiles/RIVER_LL.png")),
    RUINS(new Image("Pictures/tiles/ruins.png")),
    POPULATION(new Image("Pictures/tiles/Population.png")),

    BANANA(new Image("Pictures/resources/BANANA.png")),
    BOKHOOR(new Image("Pictures/resources/BOKHOOR.png")),
    COAL(new Image("Pictures/resources/COAL.png")),
    COLOR(new Image("Pictures/resources/COLOR.png")),
    COTTON(new Image("Pictures/resources/COTTON.png")),
    COW(new Image("Pictures/resources/COW.png")),
    DEER(new Image("Pictures/resources/DEER.png")),
    FUR(new Image("Pictures/resources/FUR.png")),
    GOLD(new Image("Pictures/resources/GOLD.png")),
    HORSE(new Image("Pictures/resources/HORSE.png")),
    IRON(new Image("Pictures/resources/IRON.png")),
    JEWELERY(new Image("Pictures/resources/JEWELERY.png")),
    MARBLE(new Image("Pictures/resources/MARBLE.png")),
    SHEEP(new Image("Pictures/resources/SHEEP.png")),
    SILK(new Image("Pictures/resources/SILK.png")),
    SILVER(new Image("Pictures/resources/SILVER.png")),
    SUGAR(new Image("Pictures/resources/SUGAR.png")),
    TUSK(new Image("Pictures/resources/TUSK.png")),
    WHEAT(new Image("Pictures/resources/WHEAT.png")),

    CULTURE_ICON(new Image("Pictures/Panels/Culture.png")),
    FAITH_ICON(new Image("Pictures/Panels/Faith.png")),
    FOOD_ICON(new Image("Pictures/Panels/Food.png")),
    GOLD_ICON(new Image("Pictures/Panels/Gold.png")),
    PRODUCTION_ICON(new Image("Pictures/Panels/Production.png")),
    SCIENCE_ICON(new Image("Pictures/Panels/Science.png")),
    HAPPINESS_ICON(new Image("Pictures/Panels/Happiness.png")),
    TURN_ICON(new Image("Pictures/Panels/Turn.png")),
    SAVE_ICON(new Image("Pictures/Icons/save.png")),
    LEFT_DOWN_PANEL_BOX(new Image("Pictures/Panels/myCiv.png")),
    STATUSBAR_BOX(new Image("Pictures/Panels/statusBar.png")),

    ACOUSTICS(new Image("Pictures/TechIcons/acoustics.png")),
    AGRICULTURE(new Image("Pictures/TechIcons/agriculture.png")),
    ANIMAL_HUSBANDRY(new Image("Pictures/TechIcons/animal_husbandry.png")),
    ARCHAEOLOGY(new Image("Pictures/TechIcons/archaeology.png")),
    ARCHERY(new Image("Pictures/TechIcons/archery.png")),
    BACKGROUND(new Image("Pictures/TechIcons/background.jpg")),
    BANKING(new Image("Pictures/TechIcons/banking.png")),
    BIOLOGY(new Image("Pictures/TechIcons/biology.png")),
    BRONZE_WORKING(new Image("Pictures/TechIcons/bronze_working.png")),
    CALENDER(new Image("Pictures/TechIcons/calendar.png")),
    CHEMISTRY(new Image("Pictures/TechIcons/chemistry.png")),
    CHIVALRY(new Image("Pictures/TechIcons/chivalry.png")),
    CIVIL_SERVICE(new Image("Pictures/TechIcons/civil_service.png")),
    COMBUSTION(new Image("Pictures/TechIcons/combustion.png")),
    CONSTRUCTION(new Image("Pictures/TechIcons/construction.png")),
    CURRENCY(new Image("Pictures/TechIcons/currency.png")),
    DYNAMITE(new Image("Pictures/TechIcons/dynamite.png")),
    ECONOMICS(new Image("Pictures/TechIcons/economics.png")),
    EDUCATION(new Image("Pictures/TechIcons/education.png")),
    ELECTRICITY(new Image("Pictures/TechIcons/electricity.png")),
    ENGINEERING(new Image("Pictures/TechIcons/engineering.png")),
    FERTILIZER(new Image("Pictures/TechIcons/fertilizer.png")),
    GUNPOWDER(new Image("Pictures/TechIcons/gunpowder.png")),
    HORSEBACK_RIDING(new Image("Pictures/TechIcons/horseback_riding.png")),
    IRON_WORKING(new Image("Pictures/TechIcons/iron_working.png")),
    MACHINERY(new Image("Pictures/TechIcons/machinery.png")),
    MASONRY(new Image("Pictures/TechIcons/masonry.png")),
    MATHEMATICS(new Image("Pictures/TechIcons/mathematics.png")),
    METAL_CASTING(new Image("Pictures/TechIcons/metal_casting.png")),
    METALLURGY(new Image("Pictures/TechIcons/metallurgy.png")),
    MILITARY_SCIENCE(new Image("Pictures/TechIcons/military_science.png")),
    MINING(new Image("Pictures/TechIcons/mining.png")),
    PHILOSOPHY(new Image("Pictures/TechIcons/philosophy.png")),
    PHYSICS(new Image("Pictures/TechIcons/physics.png")),
    POTTERY(new Image("Pictures/TechIcons/pottery.png")),
    PRINTING_PRESS(new Image("Pictures/TechIcons/printingpress.png")),
    RADIO(new Image("Pictures/TechIcons/radio.png")),
    RAILROAD(new Image("Pictures/TechIcons/railroad.png")),
    REPLACEABLE_PARTS(new Image("Pictures/TechIcons/replaceable_parts.png")),
    RIFLING(new Image("Pictures/TechIcons/rifling.png")),
    SAILING(new Image("Pictures/TechIcons/sailing.png")),
    SCIENTIFIC_THEORY(new Image("Pictures/TechIcons/scientific_theory.png")),
    STEAM_POWER(new Image("Pictures/TechIcons/steam_power.png")),
    STEEL(new Image("Pictures/TechIcons/steel.png")),
    TELEGRAPH(new Image("Pictures/TechIcons/telegraph.png")),
    THE_WHEEL(new Image("Pictures/TechIcons/the_wheel.png")),
    THEOLOGY(new Image("Pictures/TechIcons/theology.png")),
    TRAPPING(new Image("Pictures/TechIcons/trapping.png")),
    WRITING(new Image("Pictures/TechIcons/writing.png")),

    CAMP(new Image("Pictures/improvements/CAMP.png")),
    FARM(new Image("Pictures/improvements/FARM.png")),
    LUMBER_MILL(new Image("Pictures/improvements/LUMBER_MILL.png")),
    MINE(new Image("Pictures/improvements/MINE.png")),
    PASTURE(new Image("Pictures/improvements/PASTURE.png")),
    PLANTATION(new Image("Pictures/improvements/PLANTATION.png")),
    QUARRY(new Image("Pictures/improvements/QUARRY.png")),
    TRADING_POST(new Image("Pictures/improvements/TRADING_POST.png")),
    IN_PROGRESS_IMPROVEMENT(new Image("Pictures/improvements/inProgress.png")),

    CHOOSE_PRODUCTION_ICON(new Image("Pictures/cityIcons/production.png")),
    CHOOSE_RESEARCH_ICON(new Image("Pictures/cityIcons/research.png")),

    ANTI_TANK_GUN(new Image("Pictures/units/ANTI_TANK_GUN.png")),
    ARCHER(new Image("Pictures/units/ARCHER.png")),
    ARTILLERY(new Image("Pictures/units/ARTILLERY.png")),
    CANNON(new Image("Pictures/units/CANNON.png")),
    CATAPULT(new Image("Pictures/units/CATAPULT.png")),
    CAVALRY(new Image("Pictures/units/CAVALRY.png")),
    CHARIOT_ARCHER(new Image("Pictures/units/CHARIOT_ARCHER.png")),
    CROSSBOWMAN(new Image("Pictures/units/CROSSBOWMAN.png")),
    HORSEMAN(new Image("Pictures/units/HORSEMAN.png")),
    INFANTRY(new Image("Pictures/units/INFANTRY.png")),
    KNIGHT(new Image("Pictures/units/KNIGHT.png")),
    LANCER(new Image("Pictures/units/LANCER.png")),
    LONG_SWORDSMAN(new Image("Pictures/units/LONGSWORDSMAN.png")),
    MUSKET_MAN(new Image("Pictures/units/MUSKETMAN.png")),
    PANZER(new Image("Pictures/units/PANZER.png")),
    PIKE_MAN(new Image("Pictures/units/PIKEMAN.png")),
    RIFLEMAN(new Image("Pictures/units/RIFLEMAN.png")),
    SCOUT(new Image("Pictures/units/SCOUT.png")),
    SETTLER(new Image("Pictures/units/SETTLER.png")),
    SPEARS_MAN(new Image("Pictures/units/SPEARMAN.png")),
    SWORDSMAN(new Image("Pictures/units/SWORDSMAN.png")),
    TANK(new Image("Pictures/units/TANK.png")),
    TREBUCHET(new Image("Pictures/units/TREBUCHET.png")),
    WARRIOR(new Image("Pictures/units/WARRIOR.png")),
    WORKER(new Image("Pictures/units/WORKER.png")),

    AXE_ICON(new Image("Pictures/unitIcons/axe.png")),
    CAMP_ICON(new Image("Pictures/unitIcons/CAMP.png")),
    FOUND_CITY_ICON(new Image("Pictures/unitIcons/CityState.png")),
    KILL_ICON(new Image("Pictures/unitIcons/DisbandUnit.png")),
    FARM_ICON(new Image("Pictures/unitIcons/FARM.png")),
    HAMMER_ICON(new Image("Pictures/unitIcons/hammer.png")),
    DO_NOTHING_ICON(new Image("Pictures/unitIcons/Load.png")),
    LUMBER_MILL_ICON(new Image("Pictures/unitIcons/LUMBER_MILL.png")),
    MINE_ICON(new Image("Pictures/unitIcons/MINE.png")),
    PASTURE_ICON(new Image("Pictures/unitIcons/PASTURE.png")),
    PLANTATION_ICON(new Image("Pictures/unitIcons/PLANTATION.png")),
    QUARRY_ICON(new Image("Pictures/unitIcons/QUARRY.png")),
    ACTIVE_ICON(new Image("Pictures/unitIcons/Quickstart.png")),
    RAIL_ROAD_ICON(new Image("Pictures/unitIcons/railRoad.png")),
    ROAD_ICON(new Image("Pictures/unitIcons/road.png")),
    SLEEP_ICON(new Image("Pictures/unitIcons/Sleep.png")),
    STOP_ICON(new Image("Pictures/unitIcons/Stop.png")),
    TRADING_OUTPOST_ICON(new Image("Pictures/unitIcons/tradingOutpost.png")),

    ALERT_ICON(new Image("Pictures/unitIcons/military/alert.png")),
    ATTACK_ICON(new Image("Pictures/unitIcons/military/attack.png")),
    FORTIFY_ICON(new Image("Pictures/unitIcons/military/fortify.png")),
    GARRISON_ICON(new Image("Pictures/unitIcons/military/garrison.png")),
    HEAL_ICON(new Image("Pictures/unitIcons/military/heal.png")),
    PILLAGE_ICON(new Image("Pictures/unitIcons/military/Pillage.png")),
    SETUP_RANDED_ICON(new Image("Pictures/unitIcons/military/siegePrep.png")),

    DEMOGRAPHIC_PANEL_ICON(new Image("Pictures/Icons/demog.png")),
    NOTIFICATION_HISTORY_ICON(new Image("Pictures/Icons/notif.png")),
    UNITS_PANEL_ICON(new Image("Pictures/Icons/units.png")),
    ECONOMIC_PANEL_ICON(new Image("Pictures/Icons/eco.png")),
    MILITARY_OVERVIEW_PANEL_ICON(new Image("Pictures/Icons/military.jpg")),
    CITIES_PANEL_ICON(new Image("Pictures/Icons/Cities.png")),
    HEXAGON_ICON(new Image("Pictures/Icons/Hexagon.png")),

    BARRACKS(new Image("Pictures/buildingIcons/ancient/barracks.png")),
    GRANARY(new Image("Pictures/buildingIcons/ancient/granary.png")),
    LIBRARY(new Image("Pictures/buildingIcons/ancient/library.png")),
    MONUMENT(new Image("Pictures/buildingIcons/ancient/monument.png")),
    WALLS(new Image("Pictures/buildingIcons/ancient/walls.png")),
    WATER_MILL(new Image("Pictures/buildingIcons/ancient/water_mill.png")),
    ARMORY(new Image("Pictures/buildingIcons/classical/armory.png")),
    BURIAL_TOMB(new Image("Pictures/buildingIcons/classical/burial_tomb.png")),
    CIRCUS(new Image("Pictures/buildingIcons/classical/circus.png")),
    COLOSSEUM(new Image("Pictures/buildingIcons/classical/colosseum.png")),
    COURTHOUSE(new Image("Pictures/buildingIcons/classical/courthouse.png")),
    STABLE(new Image("Pictures/buildingIcons/classical/stable.png")),
    TEMPLE(new Image("Pictures/buildingIcons/classical/temple.png")),
    CASTLE(new Image("Pictures/buildingIcons/medieval/castle.png")),
    FORGE(new Image("Pictures/buildingIcons/medieval/forge.png")),
    GARDEN(new Image("Pictures/buildingIcons/medieval/garden.png")),
    MARKET(new Image("Pictures/buildingIcons/medieval/market.png")),
    MINT(new Image("Pictures/buildingIcons/medieval/mint.png")),
    MONASTERY(new Image("Pictures/buildingIcons/medieval/monastery.png")),
    UNIVERSITY(new Image("Pictures/buildingIcons/medieval/university.png")),
    WORKSHOP(new Image("Pictures/buildingIcons/medieval/workshop.png")),
    BANK(new Image("Pictures/buildingIcons/renaissance/bank.png")),
    MILITARY_ACADEMY(new Image("Pictures/buildingIcons/renaissance/military_academy.png")),
    OPERA_HOUSE(new Image("Pictures/buildingIcons/renaissance/opera_house.png")),
    MUSEUM(new Image("Pictures/buildingIcons/renaissance/museum.png")),
    PUBLIC_SCHOOL(new Image("Pictures/buildingIcons/renaissance/public_school.png")),
    SATRAPS_COURT(new Image("Pictures/buildingIcons/renaissance/satraps_court.png")),
    THEATER(new Image("Pictures/buildingIcons/renaissance/theater.png")),
    WINDMILL(new Image("Pictures/buildingIcons/renaissance/windmill.png")),
    ARSENAL(new Image("Pictures/buildingIcons/industrial/arsenal.png")),
    BROADCAST_TOWER(new Image("Pictures/buildingIcons/industrial/broadcast_tower.png")),
    FACTORY(new Image("Pictures/buildingIcons/industrial/factory.png")),
    HOSPITAL(new Image("Pictures/buildingIcons/industrial/hospital.png")),
    MILITARY_BASE(new Image("Pictures/buildingIcons/industrial/military_base.png")),
    STOCK_EXCHANGE(new Image("Pictures/buildingIcons/industrial/stock_exchange.png")),

    OPEN_TECH_TREE(new Image("Pictures/openTechTreeButton.png")),
    OPEN_DIPLOMACY_PANEL(new Image("Pictures/DiplomacyButton.png")),
    EMPLOYED_CITIZEN(new Image("Pictures/cityIcons/employed.png")),
    UNEMPLOYED_CITIZEN(new Image("Pictures/cityIcons/unemployed.png")),
    CITY_ATTACK_TARGET(new Image("Pictures/cityIcons/target.png")),
    CITY_ATTACK_LOCK(new Image("Pictures/cityIcons/lock.png")),
    CITY_PRODUCTION_MENU(new Image("Pictures/cityIcons/productionMenu.png")),

    HOME_ICON(new Image("Pictures/home.png"));

    private final Image image;

    ImageBase(Image image) {
        this.image = image;
    }

    public Image getImage() {
        return image;
    }
}
