package Model;

public enum Technology {
    AGRICULTURE, ANIMAL_HUSBANDRY, ARCHERY, BRONZE_WORKING,
    CALENDER, MASONRY, MINING, POTTERY, WHEEL, TRAPPING, WRITING,
    CONSTRUCTION, HORSE_RIDING, IRON_WORKING, MATH, PHILOSOPHY,
    CHIVALRY, CIVIL_SERVICE, EDUCATION, ENGINEERING, MACHINERY,
    METAL_CASTING, PHYSICS, STEEL, THEOLOGY, ACOUSTICS, ARCHAEOLOGY,
    BANKING, CHEMISTRY, ECONOMICS, FERTILIZER, GUNPOWDER, METALLURGY,
    MILITARY_SCIENCE, PRINTING_PRESS, RIFLING, SCIENTIFIC_THEORY,
    BIOLOGY, COMBUSTION, DYNAMITE, ELECTRICITY, RADIO, RAILROAD,
    REPLACEABLE_PARTS, STEAM_POWER, TELEGRAPH
}
